config/routes.rb
Rails.application.routes.draw do

  resources :books

  get 'books/:book_id/borrow', to: 'lendings#borrow', as: 'borrow'

  get 'books/:book_id/return', to: 'lendings#return', as: 'return'

  root 'books#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :lendings

  #extrair
  def lent_to?(user)
    lendings.where(return_date: nil, user: user).any?
  end

  def lent?
    lendings.borrowed.any?
  end

  def borrower
    lendings.borrowed.first.user
  end
end

app/models/lending.rb
class Lending < ActiveRecord::Base
  belongs_to :book
  belongs_to :user

  scope :borrowed, -> { where(return_date: nil) }
end

app/models/user.rb
class User < ActiveRecord::Base
include Clearance::User

  has_many :lendings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    Book.create book_params

    redirect_to books_path
  end

  def show
    @book = Book.find params[:id]
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :edition)
  end
end

app/controllers/lendings_controller.rb
class LendingsController < ApplicationController

  def index
    @lendings = current_user.lendings
  end

  def borrow
    Lending.create user: current_user, book: Book.find(params[:book_id]), borrow_date: Date.current

    redirect_to books_path
  end

  def return
    lending = current_user.lendings.where(book_id: params[:book_id]).first

    lending.return_date = Date.current

    if lending.valid?
      lending.save

      redirect_to books_path, notice: 'Book returned'
    else
      redirect_to books_path, alert: 'Failed to return the book'
    end
  end

  private
  def lending_params
    params.require(:lending).require(:borrow_date, :return_date, :book, :user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/lendings_helper.rb
module LendingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.erb
<div class="card">
  <%= link_to book_path(book), class: 'card-link' do %>
    <% if signed_in? && book.lent? %>
      <div class="ribbon-wrapper">
        <% if book.lent_to?(current_user) %>
          <div class="ribbon">Reading</div>
        <% else %>
          <div class="ribbon">Borrowed</div>
        <% end %>
      </div>
    <% end %>

    <div class="card-image">
      <img src="" alt="">
    </div>

    <div class="card-header">
      <%= book.name %>
    </div>
  <% end %>

  <div class="card-copy">
    <% if signed_in? %>
      <div>
        <% if book.lent_to? current_user %>
            <%= link_to 'Return', return_path(book) %>
        <% elsif book.lent? %>
            <p><%= book.borrower.email %> borrowed this book</p>
        <% else %>
            <%= link_to 'Borrow', borrow_path(book) %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/books/index.erb
<div class="cards">
  <% @books.each do |book| %>
    <%= render 'books/book', book: book %>
  <% end %>
</div>

<div>
  <%= link_to 'New Book', new_book_path %>
</div>

app/views/books/new.erb
<div>
  <%= form_for @book do |f| %>
      <p>
        <%= f.label :name %>
        <%= f.text_field :name %>
      </p>

      <p>
        <%= f.label :author %>
        <%= f.text_field :author %>
      </p>

      <p>
        <%= f.label :edition %>
        <%= f.text_field :edition %>
      </p>

      <p>
        <%= f.submit %>
      </p>
  <% end %>
</div>

app/views/books/show.erb
<div>
  <h2><%= @book.name %></h2>

  <p>
    Author: <%= @book.author %>
  </p>
  <p>
    Edition: <%= @book.edition %>
  </p>
</div>

<div>
  <h1>History</h1>
  <ul class="cards">
      <%= render @book.lendings %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheShelf</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= link_to 'Sign out', sign_out_path, :method => :delete %>
<% else %>
    <%= link_to 'Sign in', sign_in_path %>
<% end %>

<div id="flash">
  <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
  <% end %>
</div>

<%= yield %>

</body>
</html>

app/views/lendings/_lending.html.erb
<div class="card">
  <div class="card-image">
    <img src="" alt="">
  </div>
  <div class="card-header">
    <%= lending.user.email %>
  </div>
  <div class="card-copy">
    <% if lending.return_date %>
        <p>Return on <%= lending.return_date %> </p>
    <% else %>
        <p>Pending return</p>
    <% end %>
  </div>
</div>

app/views/lendings/index.erb
<div>
  <%

  %>
</div>

app/views/refills/_cards.html.erb
<div class="cards">
  <%= render 'card' %>

  <div class="card">
    <div class="ribbon-wrapper"><div class="ribbon">RIBBON</div></div>
    <div class="card-image">
      <img src="https://raw.github.com/Magnus-G/Random/master/mountains-4.png" alt="">
    </div>
    <div class="card-header">
      Another Card
    </div>
    <div class="card-copy">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
    </div>
    <div class="card-stats">
      <ul>
        <li>98<span>Items</span></li>
        <li>298<span>Things</span></li>
        <li>923<span>Objects</span></li>
      </ul>
    </div>
  </div>

  <div class="card">
    <div class="card-image">
      <img src="https://raw.github.com/Magnus-G/Random/master/mountains-3.png" alt="">
    </div>
    <div class="card-header">
      The Last Card
    </div>
    <div class="card-copy">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga, officiis sunt neque facilis culpa molestiae necessitatibus delectus veniam provident.</p>
    </div>
    <div class="card-stats">
      <ul>
        <li>98<span>Items</span></li>
        <li>298<span>Things</span></li>
        <li>923<span>Objects</span></li>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.erb
<div>
  <ul>
    <% @users.each do |user| %>
    <li>
      <%= user.name %>
    </li>
    <% end %>
  </ul>
</div>


<div>
  <%= link_to 'New User', new_user_path %>
</div>